// Version.h
#pragma once

#define VERSION_MAJOR 0
#define VERSION_MINOR 11
#define VERSION_PATCH 4
#define TYPE "Beta"

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define VERSION_STRING TOSTRING(VERSION_MAJOR) "." TOSTRING(VERSION_MINOR) "." TOSTRING(VERSION_PATCH) "-" TYPE
